# Generated by Django 4.2.5 on 2024-03-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_password_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
