# Generated by Django 4.2.5 on 2024-06-01 06:24

import apps.history.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mixins.model_translation
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=apps.history.models.generate_unique_numeric_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Наименование')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Наименование')),
                ('name_ky', models.CharField(max_length=100, null=True, verbose_name='Наименование')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
            bases=(mixins.model_translation.TranslationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.CharField(default=apps.history.models.generate_unique_numeric_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Наименование')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Наименование')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекция',
            },
            bases=(mixins.model_translation.TranslationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=apps.history.models.generate_unique_numeric_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ky', models.CharField(max_length=100, null=True)),
                ('article', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('article_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('article_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('article_ky', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='history.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='history.collection')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пост',
            },
            bases=(mixins.model_translation.TranslationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.CharField(default=apps.history.models.generate_unique_numeric_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_age', models.IntegerField(blank=True, null=True)),
                ('end_age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Года',
                'verbose_name_plural': 'Года',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='history.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='years',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='history.year'),
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='history.collection')),
            ],
        ),
    ]
