# Generated by Django 4.2.5 on 2024-05-11 13:32

import apps.history.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ky', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
            bases=(apps.history.models.TranslationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ky', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
            bases=(apps.history.models.TranslationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ky', models.CharField(max_length=100, null=True)),
                ('article', models.TextField()),
                ('article_ru', models.TextField(null=True)),
                ('article_en', models.TextField(null=True)),
                ('article_ky', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='history.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.collection')),
            ],
            bases=(apps.history.models.TranslationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_age', models.IntegerField(blank=True, null=True)),
                ('end_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='history.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='years',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='history.year'),
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collection_images/')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='history.collection')),
            ],
        ),
    ]
