# Generated by Django 4.2.5 on 2024-05-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionimage',
            old_name='auto',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='auto',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
