# Generated by Django 4.2.5 on 2024-02-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='posts_en',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='posts_ky',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='posts_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_ky',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_ru',
        ),
    ]
