# Generated by Django 4.2.5 on 2024-03-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_ky',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collection_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collection_ky',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collection_ru',
        ),
        migrations.AddField(
            model_name='collection',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='title_ky',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
