# Generated by Django 4.2.5 on 2024-02-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_remove_collection_posts_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='posts_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='history.post'),
        ),
        migrations.AddField(
            model_name='collection',
            name='posts_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='history.post'),
        ),
        migrations.AddField(
            model_name='collection',
            name='posts_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='history.post'),
        ),
    ]
