# Generated by Django 4.2.5 on 2024-12-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
