# Generated by Django 4.2.5 on 2024-02-23 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_collection_posts_en_collection_posts_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='history.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='history.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='history.category'),
        ),
    ]
